# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.dockerfile
tasks:
  - init: |
      echo "init"
      cd flask-crud && \
      python -m venv myvenv && \
      source myvenv/bin/activate && \
      python -m pip install -r requirements.txt
    command: echo "command"
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
