# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo "init"
    command: |
      curl https://packages.edgedb.com/keys/edgedb.asc  | sudo apt-key add -
      echo deb https://packages.edgedb.com/apt $(lsb_release -cs) main | sudo tee /etc/apt/sources.list.d/edgedb.list
      sudo apt-get update && sudo apt-get install edgedb-1 -y
      cd flask-crud && \
      python -m venv myvenv && \
      source myvenv/bin/activate && \
      python -m pip install -r requirements.txt
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
