# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh
    command: |
      cd flask-crud && \
      python -m venv myvenv && \
      source myvenv/bin/activate && \
      python -m pip install -r requirements.txt
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
